[package]
name = "renews"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-rustls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock"] }
tokio-rustls = "0.24"
rustls-pemfile = "1"
clap = { version = "4", features = ["derive"] }
