addr = ":119"
site_name = "example.com"
db_path = "sqlite:///var/renews/news.db"
auth_db_path = "sqlite:///var/renews/auth.db"
peer_db_path = "sqlite:///var/renews/peers.db"
peer_sync_secs = 3600
idle_timeout_secs = 600

# Article queue configuration
# article_queue_capacity = 1000    # Maximum articles in queue (default: 1000)
# article_worker_count = 4         # Number of worker threads (default: 4)

tls_addr = ":563"
tls_cert = "cert.pem"
tls_key = "key.pem"
default_retention_days = 30
default_max_article_bytes = "1M"


[[group_settings]]
pattern = "short.*"
retention_days = 7

[[group_settings]]
group = "misc.news"
retention_days = 60
max_article_bytes = "2M"

[[peers]]
sitename = "peeruser:peerpass@peer.example.com"
patterns = ["*"]
sync_interval_secs = 3600
