port = 119
site_name = "example.com"
db_path = "/var/renews/news.db"
auth_db_path = "/var/renews/auth.db"
peer_db_path = "/var/renews/peers.db"
peer_sync_secs = 3600
tls_port = 563
tls_cert = "cert.pem"
tls_key = "key.pem"
default_retention_days = 30
default_max_article_bytes = "1M"


[[group_settings]]
pattern = "short.*"
retention_days = 7

[[group_settings]]
group = "misc.news"
retention_days = 60
max_article_bytes = "2M"

[[peers]]
sitename = "peer.example.com"
patterns = ["*"]
sync_interval_secs = 3600
