port = 1199
groups = ["misc.news"]
db_path = "/var/spool/renews.db"
tls_port = 563
tls_cert = "cert.pem"
tls_key = "key.pem"
default_retention_days = 30
default_max_article_bytes = "1M"


[[group_settings]]
pattern = "short.*"
retention_days = 7

[[group_settings]]
group = "misc.news"
retention_days = 60
max_article_bytes = "2M"
