addr = ":119"
site_name = "example.com"
db_path = "sqlite:///var/renews/news.db"
auth_db_path = "sqlite:///var/renews/auth.db"
peer_db_path = "sqlite:///var/renews/peers.db"

peer_sync_schedule = "0 0 * * * *"  # Default: sync every hour
idle_timeout_secs = 600
tls_addr = ":563"
tls_cert = "cert.pem"
tls_key = "key.pem"
default_retention_days = 30
default_max_article_bytes = "1M"


[[group_settings]]
pattern = "short.*"
retention_days = 7

[[group_settings]]
group = "misc.news"
retention_days = 60
max_article_bytes = "2M"

[[peers]]
sitename = "peeruser:peerpass@peer.example.com"
patterns = ["*"]
sync_schedule = "0 */30 * * * *"  # Sync every 30 minutes

[[peers]]
sitename = "daily-peer.example.com"
patterns = ["daily.*"]
sync_schedule = "0 0 2 * * *"  # Sync daily at 2 AM
