[package]
name = "test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.24"
rcgen = "0.14"
toml = "0.8"
renews = { path = ".." }
