# Example Renews NNTP Server Configuration with Milter Support
#
# This configuration file demonstrates how to configure the Milter
# protocol filter interface for external spam and content filtering.

# Basic server configuration
addr = ":119"
site_name = "news.example.com"
db_path = "sqlite:///var/renews/news.db"
auth_db_path = "sqlite:///var/renews/auth.db"

# Optional Milter server configuration
# The Milter server address can be specified globally here
[milter]
address = "127.0.0.1:8888"          # Address of the Milter server
use_tls = false                     # Use TLS for connection to Milter server
timeout_secs = 30                   # Connection timeout in seconds

# Filter pipeline configuration
# Filters are applied in the order specified below
[[filters]]
name = "HeaderFilter"               # Validates required headers (From, Subject, Newsgroups)

[[filters]]
name = "SizeFilter"                 # Validates article size limits

[[filters]]
name = "MilterFilter"               # Apply external Milter filtering
[filters.parameters]
address = "127.0.0.1:8888"         # Override global Milter address if needed
use_tls = false                     # Override global TLS setting if needed
timeout_secs = 30                   # Override global timeout if needed

[[filters]]
name = "GroupExistenceFilter"       # Validates that target newsgroups exist

[[filters]]
name = "ModerationFilter"           # Handle moderated newsgroups

# Alternative TLS Milter configuration example
# [[filters]]
# name = "MilterFilter"
# [filters.parameters]
# address = "milter.example.com:8889"
# use_tls = true
# timeout_secs = 60

# TLS configuration (optional)
# tls_addr = ":563"
# tls_cert = "/etc/ssl/certs/server.crt"
# tls_key = "/etc/ssl/private/server.key"

# Group-specific settings
[[group_settings]]
pattern = "alt.*"
retention_days = 30
max_article_bytes = "1MB"

[[group_settings]]
pattern = "comp.*"
retention_days = 90
max_article_bytes = "5MB"